site_name: tinnitus-reconstruction
repo_url: https://github.com/alec-hoyland/tinnitus-reconstruction
site_author: Nelson Barnett
docs_dir: "docs"
theme:
    name: "material"
    logo: 'Midjourney_logo3.png'
    palette:
        primary: 'blue grey'

nav:
    - Home: index.md
    - Installation and Setup: install.md
    - Experiment:
        - Configs: experiment.md
        - Protocols: Protocols.md
        - Target Sounds: ata.md
    - Stimulus Generation:
        - Abstract classes:
            - Abstract for all classes: stimgen/AbstractStimulusGenerationMethod.md
            - Abstract for binned representations: stimgen/AbstractBinnedStimulusGenerationMethod.md
        - Bernoulli: stimgen/BernoulliStimulusGeneration.md
        - Brimijoin: stimgen/BrimijoinStimulusGeneration.md
        - Gaussian Noise With No Bins: stimgen/GaussianNoiseNoBinsStimulusGeneration.md
        - Gaussian Noise With Bins: stimgen/GaussianNoiseStimulusGeneration.md
        - Gaussian Prior: stimgen/GaussianPriorStimulusGeneration.md
        - Hierarchical Gaussian: stimgen/HierarchicalGaussianStimulusGeneration.md
        - Norena Binned: stimgen/NorenaBinnedStimulusGeneration.md
        - Norena: stimgen/NorenaStimulusGeneration.md
        - Power Distribution: stimgen/PowerDistributionStimulusGeneration.md
        - Uniform Noise With No Bins: stimgen/UniformNoiseNoBinsStimulusGeneration.md
        - Uniform Noise With Bins: stimgen/UniformNoiseStimulusGeneration.md
        - Uniform Prior Random N Bins: stimgen/UniformPriorRandomNBinsStimulusGeneration.md
        - Uniform Prior: stimgen/UniformPriorStimulusGeneration.md
        - Uniform Prior Weighted Sampling: stimgen/UniformPriorWeightedSamplingStimulusGeneration.md
    - Utilities:
        - All utilities: utils.md
    - Data Processing:
        - Scripts: scripts.md
    - Documentation Styleguide: docs_styleguide.md

use_directory_urls: true

markdown_extensions:
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.arithmatex:
        generic: true
    - toc:
          permalink: true
    - codehilite

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js