% ### view_table
% 
% Filters data table from `pilot_reconstructions.m`
% and generates a figure with a uitable for easy viewing.
% 
% **Arguments:**
%   
%   - T: `table` generated by pilot_reconstructions
% 
% **OUTPUTS:**
%  
%  - 1 figure
% 
% See Also:
% pilot_reconstructions

function view_table(T)
    
    arguments
        T table
    end

    %% Settings
    % Columns to keep
    keep = {
        'r_', ...
        'subject_ID', ...
        'target_signal', ...
        'total_trials_used'
        };

    % Stimgen settings to check for consistency
    setting_fields = {
        'n_bins', ...
        'stimuli_type', ...
        'min_bins', ...
        'max_bins'
        };

    %% Create new tables
    % Find any settings that are inconsistent across subjects
    diff_settings = table2array(varfun(@(x) length(unique(x)) > 1, T(:,setting_fields)));

    % Table with consistent settings
    T_info = T(1,setting_fields(~diff_settings));
    T_info = convertvars(T_info, @isnumeric, 'cell');

    % Data table
    T_data = [T(:, startsWith(T.Properties.VariableNames, keep)), ...
        T(:, setting_fields(diff_settings))];
    T_data = convertvars(T_data, @isnumeric, 'cell');

    %% Create figure
    fig = new_figure();


    % Table with consistent settings for reference
    col_width = cell(1, width(T_info));
    col_width(:) = {200};
    uitable(fig, 'Data', T_info{:,:}, ...
        'ColumnName', T_info.Properties.VariableNames, ...
        'RowName', T_info.Properties.RowNames, ...
        'ColumnWidth', col_width, ...
        'Units','Normalized', ...
        'Position',[0, 0, 1, 1], ...
        'FontSize', 16);

    % Data table slightly lower. 
    uitable(fig, 'Data',T_data{:,:}, ...
        'ColumnName', T_data.Properties.VariableNames, ...
        'RowName', T_data.Properties.RowNames, ...
        'Units','Normalized', ...
        'Position',[0, -0.1, 1, 1], ...
        'FontSize', 16);
    
end % function
