name: Build and deploy docs
on:
  push:
    branches:
      - main

jobs:
  printing:
    runs-on: ubuntu-latest
    steps:
      - name: show env vars
        run: |
          echo "Context is: $GITHUB_CONTEXT"
          echo "The ref is: $GITHUB_REF"
          echo "The ref_name is: ${{ github.ref_name }}"

  build:
    if: github.ref_name != 'auto-docs-pr'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build docs
        run: python code/build_docs.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Auto-update doc files'
          branch: auto-docs-pr
          delete-branch: true
          labels: documentation, automated pr

  deploy:
      if: github.ref_name == 'auto-docs-pr'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout main
          uses: actions/checkout@v3
        
        - name: Deploy docs
          uses: mhausenblas/mkdocs-deploy-gh-pages@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
